In [51]:
# Customer_Behavior_EDA_Data_Modeling

In [52]:
import pandas as pd

df = pd.read_csv('../data/Customer_retail_data.csv')

In [53]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (INR),Purchase Date,Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,8001,63,Female,Sneakers,Footwear,8798,2025-05-05 00:59:35,Mumbai,NaN,White,Spring,4.5,No,Standard,No,NaN,9,Credit Card,Monthly
1,8002,20,Female,T-Shirt,Clothing,7055,2024-07-08 17:14:19,Delhi,M,Black,Fall,2.9,No,Standard,Yes,Yes,13,Debit Card,Monthly
2,8003,46,Male,Jeans,Clothing,3071,2024-04-28 04:47:12,Mumbai,M,Red,Spring,3.4,Yes,Free Shipping,No,No,9,Debit Card,Weekly
3,8004,52,Female,Backpack,Accessories,17596,2024-10-27 15:01:27,Bengaluru,NaN,Gray,Summer,4.2,No,Standard,Yes,Yes,14,PayPal,Monthly
4,8005,56,Male,Boots,Footwear,3652,2024-04-04 22:06:55,Hyderabad,NaN,Green,Winter,4.6,Yes,Next Day Air,No,Yes,15,Apple Pay,Monthly

In [54]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             8000 non-null   int64
 1   Age                     8000 non-null   int64
 2   Gender                  8000 non-null   str
 3   Item Purchased          8000 non-null   str
 4   Category                8000 non-null   str
 5   Purchase Amount (INR)   8000 non-null   int64
 6   Purchase Date           8000 non-null   str
 7   Location                8000 non-null   str
 8   Size                    2521 non-null   str
 9   Color                   8000 non-null   str
 10  Season                  8000 non-null   str
 11  Review Rating           7880 non-null   float64
 12  Subscription Status     8000 non-null   str
 13  Shipping Type           7900 non-null   str
 14  Discount Applied        8000 non-null   str
 15  Promo Code Used         7850 non-null   str
 16  Previous Purchases      8000 non-null   int64
 17  Payment Method          8000 non-null   str
 18  Frequency of Purchases  8000 non-null   str
dtypes: float64(1), int64(4), str(14)
memory usage: 1.2 MB

In [55]:
df.describe(include = 'all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (INR),Purchase Date,Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,8000.00000,8000.000000,8000,8000,8000,8000.000000,8000,8000,2521,8000,8000,7880.000000,8000,7900,8000,7850,8000.000000,8000,8000
unique,NaN,NaN,2,10,4,NaN,8000,8,4,7,4,NaN,2,4,2,2,NaN,6,5
top,NaN,NaN,Female,Jacket,Clothing,NaN,2025-05-05 00:59:35,Mumbai,L,Blue,Fall,NaN,No,Standard,No,No,NaN,Credit Card,Monthly
freq,NaN,NaN,4180,862,2521,NaN,1,1031,659,1214,2046,NaN,5237,3879,4786,5485,NaN,3253,2787
mean,12000.50000,43.571875,NaN,NaN,NaN,27148.781250,NaN,NaN,NaN,NaN,NaN,3.973731,NaN,NaN,NaN,NaN,10.015125,NaN,NaN
std,2309.54541,14.994739,NaN,NaN,NaN,32675.447201,NaN,NaN,NaN,NaN,NaN,0.647741,NaN,NaN,NaN,NaN,3.150657,NaN,NaN
min,8001.00000,18.000000,NaN,NaN,NaN,1245.000000,NaN,NaN,NaN,NaN,NaN,1.100000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,10000.75000,31.000000,NaN,NaN,NaN,6972.000000,NaN,NaN,NaN,NaN,NaN,3.500000,NaN,NaN,NaN,NaN,8.000000,NaN,NaN
50%,12000.50000,43.000000,NaN,NaN,NaN,11620.000000,NaN,NaN,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,NaN,10.000000,NaN,NaN
75%,14000.25000,57.000000,NaN,NaN,NaN,30896.750000,NaN,NaN,NaN,NaN,NaN,4.500000,NaN,NaN,NaN,NaN,12.000000,NaN,NaN
max,16000.00000,69.000000,NaN,NaN,NaN,124251.000000,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,24.000000,NaN,NaN

In [56]:
df.isnull().sum()

Customer ID                  0
Age                          0
Gender                       0
Item Purchased               0
Category                     0
Purchase Amount (INR)        0
Purchase Date                0
Location                     0
Size                      5479
Color                        0
Season                       0
Review Rating              120
Subscription Status          0
Shipping Type              100
Discount Applied             0
Promo Code Used            150
Previous Purchases           0
Payment Method               0
Frequency of Purchases       0
dtype: int64

In [57]:
df.head(200)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (INR),Purchase Date,Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,8001,63,Female,Sneakers,Footwear,8798,2025-05-05 00:59:35,Mumbai,NaN,White,Spring,4.5,No,Standard,No,NaN,9,Credit Card,Monthly
1,8002,20,Female,T-Shirt,Clothing,7055,2024-07-08 17:14:19,Delhi,M,Black,Fall,2.9,No,Standard,Yes,Yes,13,Debit Card,Monthly
2,8003,46,Male,Jeans,Clothing,3071,2024-04-28 04:47:12,Mumbai,M,Red,Spring,3.4,Yes,Free Shipping,No,No,9,Debit Card,Weekly
3,8004,52,Female,Backpack,Accessories,17596,2024-10-27 15:01:27,Bengaluru,NaN,Gray,Summer,4.2,No,Standard,Yes,Yes,14,PayPal,Monthly
4,8005,56,Male,Boots,Footwear,3652,2024-04-04 22:06:55,Hyderabad,NaN,Green,Winter,4.6,Yes,Next Day Air,No,Yes,15,Apple Pay,Monthly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,8196,64,Female,Sneakers,Footwear,9711,2025-03-14 06:00:05,Chennai,NaN,Green,Spring,4.9,No,Next Day Air,No,No,10,Credit Card,Quarterly
196,8197,63,Female,Jacket,Clothing,5395,2024-12-04 12:02:30,Jaipur,S,Black,Summer,4.5,No,Express,No,No,21,Debit Card,Weekly
197,8198,53,Female,Backpack,Accessories,21580,2025-07-21 14:02:58,Pune,NaN,Black,Summer,4.2,Yes,Express,Yes,No,12,PayPal,Monthly
198,8199,36,Female,T-Shirt,Clothing,8466,2025-01-17 05:53:32,Jaipur,L,Brown,Spring,4.1,Yes,Next Day Air,No,Yes,8,Credit Card,Monthly
199,8200,45,Female,T-Shirt,Clothing,4316,2025-08-14 05:56:55,Pune,L,Gray,Spring,3.3,No,Standard,Yes,No,15,Apple Pay,Monthly

In [58]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [59]:
df.isnull().sum()

Customer ID                  0
Age                          0
Gender                       0
Item Purchased               0
Category                     0
Purchase Amount (INR)        0
Purchase Date                0
Location                     0
Size                      5479
Color                        0
Season                       0
Review Rating                0
Subscription Status          0
Shipping Type              100
Discount Applied             0
Promo Code Used            150
Previous Purchases           0
Payment Method               0
Frequency of Purchases       0
dtype: int64

In [60]:
df.fillna({
    'Size': 'Unknown',
    'Shipping Type': 'Not Specified',
    'Promo Code Used': 'No Promo'
}, inplace=True)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (INR),Purchase Date,Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,8001,63,Female,Sneakers,Footwear,8798,2025-05-05 00:59:35,Mumbai,Unknown,White,Spring,4.5,No,Standard,No,No Promo,9,Credit Card,Monthly
1,8002,20,Female,T-Shirt,Clothing,7055,2024-07-08 17:14:19,Delhi,M,Black,Fall,2.9,No,Standard,Yes,Yes,13,Debit Card,Monthly
2,8003,46,Male,Jeans,Clothing,3071,2024-04-28 04:47:12,Mumbai,M,Red,Spring,3.4,Yes,Free Shipping,No,No,9,Debit Card,Weekly
3,8004,52,Female,Backpack,Accessories,17596,2024-10-27 15:01:27,Bengaluru,Unknown,Gray,Summer,4.2,No,Standard,Yes,Yes,14,PayPal,Monthly
4,8005,56,Male,Boots,Footwear,3652,2024-04-04 22:06:55,Hyderabad,Unknown,Green,Winter,4.6,Yes,Next Day Air,No,Yes,15,Apple Pay,Monthly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,15996,23,Male,Headphones,Electronics,34777,2024-02-06 22:21:41,Kolkata,Unknown,Black,Winter,3.2,No,Next Day Air,No,Yes,13,PayPal,Bi-Weekly
7996,15997,45,Male,T-Shirt,Clothing,10956,2024-03-21 09:10:34,Pune,L,Gray,Spring,4.0,No,Standard,No,No,10,Credit Card,Bi-Weekly
7997,15998,57,Female,Jeans,Clothing,3569,2024-11-18 13:11:55,Mumbai,S,Blue,Fall,3.7,No,Express,Yes,Yes,17,Cash,Weekly
7998,15999,19,Female,Jacket,Clothing,6557,2024-06-30 15:44:57,Pune,M,Brown,Summer,3.2,Yes,Standard,No,No,7,Google Pay,Monthly
7999,16000,67,Male,Jeans,Clothing,11454,2024-08-03 23:28:24,Pune,XL,Brown,Summer,4.8,No,Express,No,Yes,9,Apple Pay,Weekly

In [61]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (INR)     0
Purchase Date             0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [62]:
df.duplicated().sum()

np.int64(0)

In [63]:
df[df.duplicated()]

Empty DataFrame
Columns: [Customer ID, Age, Gender, Item Purchased, Category, Purchase Amount (INR), Purchase Date, Location, Size, Color, Season, Review Rating, Subscription Status, Shipping Type, Discount Applied, Promo Code Used, Previous Purchases, Payment Method, Frequency of Purchases]
Index: []

In [64]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(inr)': 'purchase_amount'})

In [65]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'purchase_date', 'location', 'size', 'color',
       'season', 'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [66]:
# Create a column age_group

labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [67]:
df[['age', 'age_group']].head(10)

   age    age_group
0   63       Senior
1   20  Young Adult
2   46  Middle-aged
3   52  Middle-aged
4   56  Middle-aged
5   35        Adult
6   37        Adult
7   60       Senior
8   40        Adult
9   51  Middle-aged

In [68]:
# Create column purchase_frequency_days

frequency_mapping  = {
    'Fornightly' : 14,
    'Weekly' : 7,
    'Monthly' : 30,
    'Quarterly' : 90,
    'Bi-Weekly' : 14,
    'Annually' : 365,
    'Every 3 Months' : 90
}
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [69]:
df[['purchase_frequency_days', 'frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       30                Monthly
1                       30                Monthly
2                        7                 Weekly
3                       30                Monthly
4                       30                Monthly
5                       14              Bi-Weekly
6                       30                Monthly
7                       30                Monthly
8                       30                Monthly
9                      365               Annually

In [70]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0               No        No Promo
1              Yes             Yes
2               No              No
3              Yes             Yes
4               No             Yes
5              Yes              No
6               No              No
7              Yes              No
8              Yes             Yes
9               No             Yes

In [71]:
(df['discount_applied'] == df['promo_code_used']).all()

np.False_

In [72]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (2.0.47)
Requirement already satisfied: greenlet>=1 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\lenovo\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [73]:
from sqlalchemy import create_engine

#Step1: Create a connection to the PostgreSQL database
# Replace the placeholders with your actual database credentials
username = "postgres"
password = "Dakshta%4014"
host = "localhost"
port ="5432"
database = "Data Analytics Projects"

engine = create_engine(f'postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}')

#Step2: Load the DataFrame into the PostgreSQL

df.to_sql(
    name="customer",
    con=engine,
    schema="customer_behavior",   
    if_exists="replace",
    index=False
)

print(f"DataFrame loaded into PostgreSQL database '{database}' in table 'customer' successfully.")

DataFrame loaded into PostgreSQL database 'Data Analytics Projects' in table 'customer' successfully.